export function addFields(_components: any): void;
export default fieldComponents;
declare const fieldComponents: {
    Group: typeof import("./groups/group").default;
    GridGroup: typeof import("./groups/grid-group").default;
    CardGroup: typeof import("./groups/card-group").default;
    AutocompleteField: typeof AutocompleteField;
    checkbox: typeof CheckboxField;
    CheckboxField: typeof CheckboxField;
    DateRangeField: typeof DateRangeField;
    DropFileField: typeof DropFileField;
    Field: typeof Field;
    FileButtonField: typeof FileButtonField;
    FileField: typeof FileField;
    GroupField: typeof GroupField;
    hidden: typeof HiddenField;
    JsonEditorField: typeof JsonEditorField;
    NewPasswordField: typeof NewPasswordField;
    NoWrapField: typeof NoWrapField;
    PaginationField: typeof PaginationField;
    radio: typeof RadioField;
    RadioField: typeof RadioField;
    RangeField: typeof RangeField;
    select: typeof SelectField;
    SelectField: typeof SelectField;
    SwitchField: typeof SwitchField;
    TextareaField: typeof TextareaField;
};
import AutocompleteField from "./fields/autocomplete-field";
import CheckboxField from "./fields/checkbox-field";
import DateRangeField from "./fields/date-range-field";
import DropFileField from "./fields/drop-file-field";
import Field from "./fields/field";
import FileButtonField from "./fields/file-button-field";
import FileField from "./fields/file-field";
import GroupField from "./fields/group-field";
import HiddenField from "./fields/hidden-field";
import JsonEditorField from "./fields/json-editor-field";
import NewPasswordField from "./fields/new-password-field";
import NoWrapField from "./fields/no-wrap-field";
import PaginationField from "./fields/pagination-field";
import RadioField from "./fields/radio-field";
import RangeField from "./fields/range-field";
import SelectField from "./fields/select-field";
import SwitchField from "./fields/switch-field";
import TextareaField from "./fields/textarea-field";
