export function addComponents(newComponents: any): void;
export default COMPONENTS;
declare const COMPONENTS: {
    Group: typeof import("./forms/groups/group").default;
    GridGroup: typeof import("./forms/groups/grid-group").default;
    CardGroup: typeof import("./forms/groups/card-group").default;
    AutocompleteField: typeof import("./forms/fields/autocomplete-field").default;
    checkbox: typeof import("./forms/fields/checkbox-field").default;
    CheckboxField: typeof import("./forms/fields/checkbox-field").default;
    DateRangeField: typeof import("./forms/fields/date-range-field").default;
    DropFileField: typeof import("./forms/fields/drop-file-field").default;
    Field: typeof import("./forms/fields/field").default;
    FileButtonField: typeof import("./forms/fields/file-button-field").default;
    FileField: typeof import("./forms/fields/file-field").default;
    GroupField: typeof import("./forms/fields/group-field").default;
    hidden: typeof import("./forms/fields/hidden-field").default;
    JsonEditorField: typeof import("./forms/fields/json-editor-field").default;
    NewPasswordField: typeof import("./forms/fields/new-password-field").default;
    NoWrapField: typeof import("./forms/fields/no-wrap-field").default;
    PaginationField: typeof import("./forms/fields/pagination-field").default;
    radio: typeof import("./forms/fields/radio-field").default;
    RadioField: typeof import("./forms/fields/radio-field").default;
    RangeField: typeof import("./forms/fields/range-field").default;
    select: typeof import("./forms/fields/select-field").default;
    SelectField: typeof import("./forms/fields/select-field").default;
    SwitchField: typeof import("./forms/fields/switch-field").default;
    TextareaField: typeof import("./forms/fields/textarea-field").default;
    Container: typeof import("./containers/container").default;
    AlertContainer: typeof import("./containers/alert-container/alert-container").default;
    AspectRatioContainer: typeof import("./containers/proportional-container").default;
    CardContainer: typeof import("./containers/card-container").default;
    DetailsContainer: typeof import("./containers/details-container").default;
    DropdownButtonContainer: typeof import("./containers/dropdown-button-container").default;
    DropdownContainer: typeof import("./containers/dropdown-container").default;
    FetchContainer: typeof import("./containers/fetch-container").default;
    FooterContainer: typeof import("./containers/footer-container").default;
    FormContainer: typeof import("./containers/form-container").default;
    FullscreenContainer: typeof import("./containers/fullscreen-container").default;
    GridContainer: typeof import("./containers/grid-container").default;
    GridSwitchContainer: typeof import("./containers/grid-switch-container").default;
    JsonRenderContainer: typeof import("./containers/json-render-container").default;
    ListContainer: typeof import("./containers/list-container").default;
    ModalButtonContainer: typeof import("./containers/modal-button-container").default;
    ModalContainer: typeof import("./containers/modal-container").default;
    OffcanvasContainer: typeof import("./containers/offcanvas/offcanvas").default;
    PanelContainer: typeof import("./containers/panel-container/panel-container").default;
    ProportionalContainer: typeof import("./containers/proportional-container").default;
    SchemaContainer: typeof import(".").SchemaContainer;
    ScrollContainer: typeof import("./containers/scroll-container").default;
    SlideContainer: typeof import("./containers/slide-container").default;
    TableContainer: typeof import("./containers/table-container").default;
    TabsContainer: typeof import("./containers/tabs-container").default;
    FloatingContainer: typeof import("./containers/floating-container/floating-container").default;
    Action: typeof Action;
    BrandNavigation: typeof BrandNavigation;
    Component: typeof Component;
    Form: typeof Form;
    Icons: typeof Icons;
    SvgImports: (props: any) => JSX.Element;
    Image: typeof Image;
    Link: typeof Link;
    MenuItem: typeof MenuItem;
    Navigation: typeof Navigation;
    NavLink: typeof NavLink;
    Table: typeof Table;
    ToggleTextNavigation: typeof ToggleTextNavigation;
    Video: typeof Video;
    YoutubeVideo: typeof YoutubeVideo;
    Route: typeof Route;
};
import Action from "./actions/action";
import BrandNavigation from "./navigation/brand-navigation";
import Component from "./component";
import Form from "./forms/form";
import Icons from "./media/icons";
import Image from "./media/image";
import Link from "./navigation/react-router-link";
import MenuItem from "./navigation/menu-item/menu-item";
import Navigation from "./navigation/navigation";
import NavLink from "./navigation/react-router-navlink";
import Table from "./tables/table";
import { ToggleTextNavigation } from "./navigation/navigation";
import Video from "./media/video";
import YoutubeVideo from "./media/youtube-video";
import Route from "./react-router-schema/route";
