export default class Field extends Component {
    static propTypes: {
        accept: any;
        autoComplete: any;
        checkValidity: any;
        controlClasses: any;
        default: any;
        disabled: any;
        errorMessage: any;
        first: any;
        floating: any;
        hidden: any;
        inline: any;
        inlineControlClasses: any;
        label: any;
        labelClasses: any;
        max: any;
        message: any;
        messageClasses: any;
        min: any;
        multiple: any;
        noValidate: any;
        pattern: any;
        placeholder: any;
        readOnly: any;
        required: any;
        step: any;
        type: any;
        value: any;
        options: any;
        _props: any;
        active: any;
        children: any;
        classes: any;
        name: any;
        style: any;
        tag: any;
    };
    static defaultProps: {
        type: string;
        default: string;
        value: string;
        first: string;
        floating: boolean;
        classes: string;
        style: {};
        active: boolean;
    };
    unique: string;
    state: {
        value: any;
        options: any;
        error: boolean;
        pristine: boolean;
        dirty: boolean;
    };
    ContentWrap: string;
    onChange(e: any): void;
    onInvalid(): void;
    onUpdate(updateObj: any): any;
    input: import("react").RefObject<any>;
    componentDidMount(): void;
    componentWillUnmount(): void;
    extractString(obj: any): any;
    returnData(value: any, extra: any): void;
    _reset: boolean | undefined;
    timeoutReturnData: number | undefined;
    isInvalid(value: any): any;
    timeoutRevalidate: number | undefined;
    onFocus: () => void;
    get type(): any;
    get inputProps(): any;
    get labelNode(): any;
    get inputNode(): any;
    get errorMessageNode(): any;
    get messageNode(): any;
}
import Component from "../../component";
