export default class NewPasswordField extends Field {
    static propTypes: {
        labelRepeat: any;
        placeholderRepeat: any;
        dividerClasses: any;
        patterns: any;
        mutations: any;
        accept: any;
        autoComplete: any;
        checkValidity: any;
        controlClasses: any;
        default: any;
        disabled: any;
        errorMessage: any;
        first: any;
        floating: any;
        hidden: any;
        inline: any;
        inlineControlClasses: any;
        label: any;
        labelClasses: any;
        max: any;
        message: any;
        messageClasses: any;
        min: any;
        multiple: any;
        noValidate: any;
        pattern: any;
        placeholder: any;
        readOnly: any;
        required: any;
        step: any;
        type: any;
        value: any;
        options: any;
        _props: any;
        active: any;
        children: any;
        classes: any;
        name: any;
        style: any;
        tag: any;
    };
    static defaultProps: {
        dividerClasses: string;
        type: string;
        default: string;
        value: string;
        first: string;
        floating: boolean;
        classes: string;
        style: {};
        active: boolean;
    };
    jsonRender: JsonRender;
    get type(): string;
    onUpdateRepeat: (data: any) => void;
    isInvalid(value?: any, valueRepeat?: any): any;
}
import Field from "./field";
import JsonRender from "../../json-render";
