export default class DropFileField extends Field {
    static propTypes: {
        onDragOver: any;
        onDragLeave: any;
        onDrop: any;
        accept: any;
        autoComplete: any;
        checkValidity: any;
        controlClasses: any;
        default: any;
        disabled: any;
        errorMessage: any;
        first: any;
        floating: any;
        hidden: any;
        inline: any;
        inlineControlClasses: any;
        label: any;
        labelClasses: any;
        max: any;
        message: any;
        messageClasses: any;
        min: any;
        multiple: any;
        noValidate: any;
        pattern: any;
        placeholder: any;
        readOnly: any;
        required: any;
        step: any;
        type: any;
        value: any;
        options: any;
        _props: any;
        active: any;
        children: any;
        classes: any;
        name: any;
        style: any;
        tag: any;
    };
    onInvalid(e: any): void;
    onDragover: () => void;
    onDragleave: () => void;
    onUpdate(update: any): void;
    get type(): string;
}
import Field from "./field";
